### ISSUE TITLE
Ability to recall / save settings

### ISSUE THREAD

**Issue by bradgarropy** [stevebauman/showcode#14]
💜 Seriously love this tool!

I would love to be able to easily recall the settings of past code exports. Maybe the initial implementation can be as simple as saving the last known settings in `localStorage`?

Thanks for considering this feature!

**Comment by stevebauman** [comment]
Thanks so much for your kind words @bradgarropy! Glad you find it useful 😄 

I'm definitely going to add this in -- it's just a matter of time. Hopefully in the next couple weeks I'll have it up and running 👍

**Comment by bradgarropy** [comment]
I'm a seasoned `react` developer, but I'm new to Vue. If you point me to the right file(s) I can create a branch and try submitting a PR!

**Comment by stevebauman** [comment]
Sure! That'd be awesome. If you'd like to take a crack at it, here's all the settings for the preview window:

https://github.com/stevebauman/showcode/blob/4d570f022c7ef098c73a9eb9a075ef80b9d14959/components/Preview.vue#L408-L436

I've also added local installation instructions to get you up and running:

https://github.com/stevebauman/showcode#local-installation

**Comment by nik-418** [comment]
+1 for a simple localStorage implementation!

**Comment by stevebauman** [comment]
Implemented! All settings and all tabs are now stored by default in local storage (try making changes, closing the browser window, and then re-visiting showcode.app).

You can now save a tab as a template so you can create new project/screenshots based on the exact same template! 🎉

**Comment by bradgarropy** [comment]
Woah that was fast, thank you so much @stevebauman!
