### ISSUE TITLE
Add additional (horizontal) padding options for the code window

### ISSUE THREAD

**Issue by stevebauman** [stevebauman/showcode#143]
https://twitter.com/ericlbarnes/status/1547956046169137157

**Comment by ericlbarnes** [comment]
To add a little more details here. What we do for all the featured images is a set width/height, so every image is 2200x1100. 

Then for code images, I like the code window to cover almost all the background with just a little background showing. Here are two examples: 

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/116662/179253943-f1994ab9-0c26-40d4-be91-f2d50d5e1a48.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/116662/179253180-292d95c5-8c80-447f-970d-65377f5aac2f.png">

I think with a horizontal padding option. I could then manually set the padding enough to get this same effect.

**Comment by stevebauman** [comment]
Okay excellent, thanks for posting the extra details! 👍

**Comment by stevebauman** [comment]
Ok all done @ericlbarnes!

You can now adjust the window border radius (per corner), window padding (per side) and window position, allowing you to (hopefully) create code images easily in the Laravel News style:

![image](https://user-images.githubusercontent.com/6421846/180661330-2405c204-4fd4-42c5-b45f-91771f104cc9.png)

Working on deploying a new Showcode Desktop version as I type this, so it should be released shortly. Let me know if you need any other features, or if I missed something. Thanks! 😄
