### ISSUE TITLE
SVGs opening as blank documents in vector editing software

### ISSUE THREAD

**Issue by lessonhacker** [stevebauman/showcode#16]
In multiple vector editing applications the SVG opens as an empty file in the correct proportions, in particular neither Adobe Illustrator CC 2022 (Mac) or Inkscape can open these files.

**Comment by stevebauman** [comment]
Hi @lessonhacker! You're right -- I can't even open the SVG's in photopea.com. Let me get this fixed 👍

**Comment by stevebauman** [comment]
Okay, this is apparently going to be near impossible to fix due to show shiki generates tokens. I investigated very thoroughly, and no one has been able to export shiki tokens to SVG, even on the [shiki playground](https://shiki-play.matsu.io/play) site, SVG's don't get generated properly.

We'll have to wait on this one 👍

**Comment by stevebauman** [comment]
I've also tried using [paid software](https://www.hiqpdf.com/demo/ConvertHtmlToSvg.aspx), but even it can't handle processing shiki tokens...

**Comment by lupinitylabs** [comment]
Maybe it's a good idea to disable SVG export altogether... 
Looking at the SVG source, it's basically HTML & CSS wrapped in an SVG tag. That's not really helpful... and also misleading. I am tempted to always save and keep a format that's scalable and lossless, but now I'm glad I didn't use SVG export. 😅

**Comment by lessonhacker** [comment]
Maybe just rename it as HTML export - as I’ve found it really useful to dump the HTML for further manipulation.

**Comment by stevebauman** [comment]
This may be the ticket: https://www.npmjs.com/package/dom-to-svg

**Comment by stevebauman** [comment]
Results aren't perfect using `dom-to-svg`, but they're the best I've seen.

Is the below good enough for you guys?

![Untitled-1](https://user-images.githubusercontent.com/6421846/215615897-ef1c85c6-42e3-429b-9004-6cf192904406.svg)

**Comment by lupinitylabs** [comment]
I don't know how it looks for you, but it's completely shot in Firefox:

![grafik](https://user-images.githubusercontent.com/17774818/215627467-f54e9257-e139-4b57-9872-cdc3893ecb5c.png)

**Comment by stevebauman** [comment]
Yea it’s similar to that (on my phone at the moment so can’t post screenshot of Chrome example). Looks like the tech is getting there but not entirely yet.

I’ll keep this issue closed for the time being. I may dive into this package and see if I can commit any PRs to resolve these issues.
