### ISSUE TITLE
Copy Image Cannot read properties of undefined (reading 'write')

### ISSUE THREAD

**Issue by weihongbin1** [stevebauman/showcode#176]
`Cannot read properties of undefined (reading 'write')
An error occurred while rendering the page. Check developer tools console for details.`
![image](https://user-images.githubusercontent.com/29483265/205895407-1f168cb1-0e32-41ca-bd4e-5176e33fbf4f.png)
![image](https://user-images.githubusercontent.com/29483265/205895437-0cfc2c53-beae-4657-b360-659a2fe5c900.png)
![image](https://user-images.githubusercontent.com/29483265/205895505-10ac5993-4d36-4174-a460-ccafbc5ef13a.png)

**Comment by stevebauman** [comment]
Hi @weihongbin1!

What web browser are you using? It looks like it doesn't support the clipboard API?

I'll patch this so the copy button displays a tooltip if the browser doesn't support it 👍

**Comment by weihongbin1** [comment]
> Hi @weihongbin1!
> 
> What web browser are you using? It looks like it doesn't support the clipboard API?
> 
> I'll patch this so the copy button displays a tooltip if the browser doesn't support it 👍

Google Chrome Version 108.0.5359.95 (Official Build) (64-bit)
