### ISSUE TITLE
(support | paid app) Title on the window header does not update

### ISSUE THREAD

**Issue by wkhayrattee** [stevebauman/showcode#180]
Hello,

just bought the desktop version, I cannot seem to be able to update the title despite I click on "Change Project Name", see screenshot below:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7369626/210790486-ee703062-dabe-436e-8c8e-b62ed4089a3c.png">

How to change? I can only see the following option:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/7369626/210790773-2339a151-2143-4b2b-b5b6-2670a40f6e36.png">

**Comment by stevebauman** [comment]
Hi @wkhayrattee,

Thanks for your support! ❤️ 

If you click into the text on the code window, you should be able to change it:

https://user-images.githubusercontent.com/6421846/210799816-ffb82597-e845-4a57-962f-cc6b274ec925.mp4

Let me know if you encounter any issues doing this 👍

**Comment by wkhayrattee** [comment]
@stevebauman yes that worked, just tried.

Urm, may be put a cursor on click to make it intuitive that it's editable - as I did click and thought that was not the case.
Closing this ticket now, thanks and Happy New Year to you fam!

Cheers
