### ISSUE TITLE
Question: What is the default font family?

### ISSUE THREAD

**Issue by zhangqi0131** [stevebauman/showcode#192]
![image](https://github.com/stevebauman/showcode/assets/77319544/036b2a25-d415-49cb-a0cf-68d902c6bc1c)

**Comment by stevebauman** [comment]
Hi @zhangqi0131,

Showcode uses the `font-mono` Tailwind class to style the "Default" font selection. This means the font will be the first available on your OS, as shown in the Tailwind docs:

https://tailwindcss.com/docs/font-family

```
font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
```
