### ISSUE TITLE
Add support for "conf" format

### ISSUE THREAD

**Issue by khalyomede** [stevebauman/showcode#195]
Hi, thank you for this great app! I wanted to show a Supervisor conf snippet, but the format is not listed. Here is a file example (looks like Github does not support it either, it works on VSCode by the way):

```conf
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/forge/app.com/artisan queue:work sqs --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=forge
numprocs=8
redirect_stderr=true
stdout_logfile=/home/forge/app.com/worker.log
stopwaitsecs=3600
```

Working example on VSCode (through md format)

![image](https://github.com/stevebauman/showcode/assets/15908747/51ae2c06-0dd4-481e-ac68-476e56134255)

**Comment by stevebauman** [comment]
Hi @khalyomede, thanks, I'm glad you like Showcode!

Showcode uses Shiki under the hood for syntax highlighting, and `conf` it is not listed there as a supported language:

https://github.com/shikijs/shiki/blob/main/docs/languages.md

We'll have to add it as a custom language, though I'm not sure where that language would be located/hosted. Do you have an idea?

**Comment by khalyomede** [comment]
Hey @stevebauman, thanks for the clarification!

I may give a try to open an issue on https://github.com/shikijs/shiki to add support for this format what do you think about it?

**Comment by stevebauman** [comment]
Sure you can give it a shot!

Though, maybe `.ini` is what you're looking for? Seems to provide very similar highlighting:

<img width="1840" alt="Screenshot 2023-11-22 at 4 00 33 PM" src="https://github.com/stevebauman/showcode/assets/6421846/2a60d3e5-34ff-4a99-b8b8-73de6bf9cd04">

**Comment by stevebauman** [comment]
With `github-dark-dimmed`:
![image](https://github.com/stevebauman/showcode/assets/6421846/9974a31e-ea79-4ee0-81bd-874f422e1986)

**Comment by khalyomede** [comment]
Oh, that is actually just perfect! Thank you :rocket: I will close this one for now.

**Comment by stevebauman** [comment]
Perfect! No problem, always happy to help 🙏

**Comment by stevebauman** [comment]
I'll add `conf` in the list as an alias for `ini` for others in the future 👍
