### ISSUE TITLE
Misalignment in "Fit to Window" Center Position

### ISSUE THREAD

**Issue by BuczynskiRafal** [stevebauman/showcode#205]
The "Fit to Window" feature incorrectly centers content by an offset of 5-10 px when "Position" is set to "Center", resulting in the right and top edges of the image being clipped. Additionally, the "Margin Properties" are not functioning correctly, further affecting the display and positioning of content on the screen.

https://github.com/stevebauman/showcode/assets/26636589/0e557bc6-5e7c-4cdd-80d0-872cfc270ce1

**Comment by stevebauman** [comment]
Thanks for the report @BuczynskiRafal! I'm able to replicate, seems to be a regression bug from some tweaks I made a couple weeks ago. Fixing now 🙏

**Comment by stevebauman** [comment]
Ok I've just made a new release on web to resolve this. I'll have a new release for the desktop app out tomorrow morning (if you're using it). Let me know if you encounter any further issues 🙏

**Comment by BuczynskiRafal** [comment]
OMG. I wish someday I could implement fixes that fast :D

**Comment by stevebauman** [comment]
Haha thanks @BuczynskiRafal! 😄 🙏
