### ISSUE TITLE
Add highlight / color, transparent backgrounds

### ISSUE THREAD

**Issue by BuczynskiRafal** [stevebauman/showcode#207]
Currently, the background of the code snippet container in the application is transparent, which causes it to blend into the application window and makes it difficult to see. Currently, only short lines are visible. Is it possible to highlight into a transparent background?

**Comment by stevebauman** [comment]
Hey @BuczynskiRafal!

Could you give me an example of what you'd like to see? I want to make sure I'm understanding what you're looking for before changing 👍

**Comment by BuczynskiRafal** [comment]
Forgive me for not specifying. I am sending a scren. I mean to cut off the snippet background from the application window. What do you think about it?

![image](https://github.com/stevebauman/showcode/assets/26636589/5e295f05-ff37-4763-8f03-aa7a03f9b380)

**Comment by stevebauman** [comment]
Ohh I see, yes we can absolutely do that. I'll change the transparent background opacity 👍

**Comment by BuczynskiRafal** [comment]
Thanks

**Comment by stevebauman** [comment]
Done! The transparent background is now much clearer. Let me know if you think it needs any other adjustements:

<img width="1031" alt="Screenshot 2024-05-27 at 8 07 41 PM" src="https://github.com/stevebauman/showcode/assets/6421846/b991bbaf-d1c7-487b-a4bd-43d1c2ff1346">
<img width="1031" alt="Screenshot 2024-05-27 at 8 07 38 PM" src="https://github.com/stevebauman/showcode/assets/6421846/1f6d6b9d-9504-49ce-be70-b67936f611f4">

**Comment by BuczynskiRafal** [comment]
It looks great. I think you can still add a line on the edge of the background. What do you think about it? Maybe it is unnecessary, I don't know myself. 

![image](https://github.com/stevebauman/showcode/assets/26636589/0dadba5d-3fb3-4474-8d94-959f3ec15d33)
![image](https://github.com/stevebauman/showcode/assets/26636589/411933c4-1773-4564-81e8-e707ea5a676e)

**Comment by stevebauman** [comment]
Hey @BuczynskiRafal, yea I like that! Let me add that in 👍

**Comment by BuczynskiRafal** [comment]
It looks great. I have tested on production and it is very helpful in preparing uniform size sinppets.

**Comment by stevebauman** [comment]
Excellent, glad to hear! 🙏
