### ISSUE TITLE
"Copy image" button does not work anymore

### ISSUE THREAD

**Issue by lyrixx** [stevebauman/showcode#211]
Thanks for this awesome tools, but it does not anymore on my computer for few weeks / months now.

## The "Copy image" button, does not work anymore

Output of the console:
```
Uncaught (in promise) DOMException: Failed to execute 'write' on 'Clipboard': Invalid Blob types.
Promise.then
copy @ afae0a8.js:2
Promise.then
copyToClipboard @ afae0a8.js:2
click @ afae0a8.js:2
ee @ bbb6f3d.js:2
n @ bbb6f3d.js:2
Dr.c._wrapper @ bbb6f3d.js:2
```

## The "Export image" button, does not work anymore

I produce an empty file

## Preview issue

Then, I notice something strange, there is a cross in the middle of the preview
![image](https://github.com/user-attachments/assets/ccc91585-2776-4b76-bd3e-0b7577f49fae)

1. I cleaned all the configuration / local storage etc
2. Ubuntu 22.04.4 LTS
3. Chome Version 127.0.6533.72 (Official Build) (64-bit)

**Comment by lyrixx** [comment]
For the record, I just tested with a fresh FireFox, and it does not work either

**Comment by lyrixx** [comment]
Oh, @damienalexandre found what does not work. It's the button "fit to windows" that reduce the size to 0x0. If I manually change it, the "cross" disappear, and I'm able to copy the image.

**Comment by stevebauman** [comment]
Ah this was my mistake @lyrixx, I accidentally removed the `actualWidth` and `actualHeight` functions in a previous commit 😅 :

https://github.com/stevebauman/showcode/commit/d0bfa1b5fff9bd7ab85ea2b26dc70106beeed02a#diff-bd02c987b90c0a00a40df93cc179af3be2e0c2012e7ab3a095a6be3c72887d83L333-L334

**Comment by lyrixx** [comment]
Will you revert this? Since you closed my PR, I have not any working playground anymore :)

**Comment by stevebauman** [comment]
Apologies @lyrixx, forgot to close this -- I've released a patch that is in production right now and have also updated the desktop app.

You're all set!
