### ISSUE TITLE
Ability to generate images via API

### ISSUE THREAD

**Issue by stevebauman** [stevebauman/showcode#31]

**Comment by bdsoha** [comment]
Another great option would generation via CLI. 
I could imaging one common use-case, dynamically generating code snippets for documentation in CI.

**Comment by stevebauman** [comment]
Thanks for the suggestion @bdsoha! I think that’s a great idea. Though, I think it would have to use the API. The only way I could see CLI generations working locally would be to have Showcode web running and using Puppetteer or something.

The API is coming along nicely. Hoping to launch early in the new year 🙏

**Comment by stevebauman** [comment]
Completed! 🎉 

https://api.showcode.app/docs
