### ISSUE TITLE
Line number issue

### ISSUE THREAD

**Issue by cadlec** [stevebauman/showcode#4]
![JavaScript class example](https://user-images.githubusercontent.com/25343854/139666719-fed0a968-34e8-4216-a324-7db8edbf70ef.png)

Hello
Good job @stevebauman !!!
Just notify line number has some bugs.

**Comment by stevebauman** [comment]
Hi @cadlec, thank you for your kind words! 😄 

Which browser did you take this screenshot in?

**Comment by stevebauman** [comment]
Ah never mind! I'm able to reproduce this, thank you for the report! Will have a fix shortly 👍

**Comment by cadlec** [comment]
Ok, great! thank you
