### ISSUE TITLE
Being able to flip code and preview

### ISSUE THREAD

**Issue by doekenorg** [stevebauman/showcode#50]
I'm probably a bit weird like this, but I would love to be able to code on the right side. 

Somehow my wires get crossed when I "code" on the left, and see the results on the right.

**Comment by stevebauman** [comment]
This should be pretty easily implemented -- we can add another toolbar button to use `flex-row-reverse` instead of `flex-row`:

https://github.com/stevebauman/showcode/blob/d4f326b42e0393434194c64c37d899caafa06825/components/Page.vue#L5

**Comment by stevebauman** [comment]
![Screen Shot 2021-11-23 at 11 34 11 AM](https://user-images.githubusercontent.com/6421846/143065153-cb09ab24-35b6-4bae-a608-8f9367cb4f1a.png)

**Comment by stevebauman** [comment]
Done! 😄 

![Screen Shot 2022-02-04 at 3 59 36 PM](https://user-images.githubusercontent.com/6421846/152602362-12b7f280-43c0-4b62-87a6-b2cfd068c9de.png)

**Comment by doekenorg** [comment]
Nice @stevebauman. You're a flexbox wizard ;-) 🧙

**Comment by stevebauman** [comment]
Haha thanks @doekenorg!
