### ISSUE TITLE
Can't drag the window horizontally to make the image wider

### ISSUE THREAD

**Issue by swanson** [stevebauman/showcode#62]
https://user-images.githubusercontent.com/56947/144481238-d09bed5b-30aa-4ed6-bccd-026591ebface.mov

Often I'd like to have more of the background gradient shown so I want to make the image wider, but keep the code the same. It looks like this should work by dragging the side handles, but it doesnt.

The only way I can hack around it is to add a bunch of padding and then scale the padding back down

**Comment by stevebauman** [comment]
Hey @swanson! Thanks for the report 😄 

Ah, I have hard-coded max width's and heights here:

https://github.com/stevebauman/showcode/blob/d4cebec50738f62849ef9b1421a4bb193c78ca72/components/Preview.vue#L601-L603

https://github.com/stevebauman/showcode/blob/d4cebec50738f62849ef9b1421a4bb193c78ca72/components/Preview.vue#L624-L626

I'll get rid of these 👍
