### ISSUE TITLE
Add Hypercolor gradients

### ISSUE THREAD

**Issue by swanson** [stevebauman/showcode#68]
https://hypercolor.dev/

Particularly the ones in the Mesh and Grainy tabs are neat and work great for code screenshots

**Comment by stevebauman** [comment]
Oh wow these are gorgeous gradients! Definitely going to add these in, thanks for the link @swanson! 😄

**Comment by stevebauman** [comment]
Completed: https://github.com/stevebauman/showcode/pull/91
