### ISSUE TITLE
Performance issues in Google Chrome

### ISSUE THREAD

**Issue by markwalet** [stevebauman/showcode#69]
Hey there, first of all: loving the app.

I used the app today and saw that there were some updates. This new version, however, had some performance issues in Chrome for me. In Firefox, the app works fine. The issue was encountered today for the first time, but the preview time I used it was October 16th. Back then, the performance issues weren't showing yet.

The performance issues start when I want to type some new code in the editor. All other buttons and options work fine for me. When typing, it can take up to 20 seconds before the code is shown in the editor. This is fine when it only happens in the preview. But the editor itself should be performant IMO.

<details>
  <summary>Export of configuration</summary>

```json
{
  "tab": {
    "id": "ed1005d4-b60c-4164-825d-6297713ea1a4",
    "created_at": "2021-12-10T10:07:29.435Z",
    "name": "Advent of Code"
  },
  "page": {
    "editors": [
      {
        "id": "57bfdd34-e361-46d0-a52f-05502fce70e9",
        "tabSize": 4,
        "language": "php",
        "value": "<?php\n\n$input = explode(PHP_EOL, file_get_contents('puzzle-input.txt'));\n\n$answer = collect($input)\n    ->map(fn (string $line) => new LineSyntaxChecker($line))\n    ->each(fn (LineSyntaxChecker $line) => $line->validate())\n    ->reject(fn (LineSyntaxChecker $line) => $line->isValid())\n    ->groupBy(fn (LineSyntaxChecker $line) => $line->errorScore())\n    ->map(fn (Collection $lines, int $score) => $score * $lines->count())\n    ->sum();\n\necho 'hello world';"
      }
    ],
    "sizes": [
      40,
      60
    ],
    "orientation": "landscape",
    "previousOrientation": null
  },
  "settings": {
    "width": 799,
    "height": 408,
    "showHeader": true,
    "showTitle": true,
    "showShadow": true,
    "showColorMenu": true,
    "showLineNumbers": false,
    "background": "conic-26",
    "backgroundPadding": "32",
    "themeType": "dark",
    "themeOpacity": 1,
    "themeName": "material-default",
    "themeBackground": "rgba(38,50,56,1)",
    "borderRadius": 12,
    "fontSize": 16,
    "lineHeight": "22",
    "padding": "16"
  }
}
```
</details>

I did a performance run in Chrome. If you open the image in a new tab, you may see something useful there. I'm not sure what I'm looking at but I thought I'd share it anyway.

<details>
  <summary>Screenshot of performance run in Chrome</summary>

![image](https://user-images.githubusercontent.com/11446771/145559544-8411715c-d303-4858-bd3e-19d0e046c694.png)
</details>

If there is any more information you need of tests I can run for you, please let me know. I'm not sure what is causing this problem. If I have to take a wild guess, the image gets regenerated on every keypress and Chrome sends a lot of power to that rendering process.

**Comment by stevebauman** [comment]
Thanks @markwalet! I think this calls for a `_.debounce()` on the preview so continuous key presses (like you mention) don't generate the shiki tokens immediately in the preview.

Going to label this as a bug -- I'll have a PR out shortly! 😄

**Comment by stevebauman** [comment]
Can you give this preview a shot and let me know if you experience better performance?

https://deploy-preview-70--festive-hermann-8f687a.netlify.app/

**Comment by markwalet** [comment]
Works fine on my side :)

What we maybe could do in a future improvement is only start a new render when the previous render is finished. instead of with a fixed debounce rate. That way, more performant clients get quicker previews, but mainly, lower-end clients (with renderer times longer than 500 ms) will not suffer on performance.

For now this works just fine :+1:

**Comment by stevebauman** [comment]
> Works fine on my side :)

Excellent!

> What we maybe could do in a future improvement is only start a new render when the previous render is finished.

This is actually already implemented with the queue system. All shiki methods are contained inside a queued function with a concurrency of one (1), so each queued function must complete prior to proceeding functions completing:

https://github.com/stevebauman/showcode/blob/115a6d9ed7d1f8cc8789f998848a8e91564006a0/components/Preview.vue#L763-L787

https://github.com/stevebauman/showcode/blob/115a6d9ed7d1f8cc8789f998848a8e91564006a0/plugins/queue.js#L1-L10

Is this sort of what you were thinking of?

**Comment by markwalet** [comment]
Hmm, without the debounce this actually pushes a lot of jobs to the queue. Explains the long running time.

Instead of this, you actually should prevent pushing a job to the queue if the process is already running. That way you can remove the debounce again, and have nearly instant rendering.

**Comment by stevebauman** [comment]
> Instead of this, you actually should prevent pushing a job to the queue if the process is already running.

If I did that, the last keystrokes in the editor wouldn't appear in the preview since the jobs wouldn't be pushed to render them. How would I go about that?

**Comment by markwalet** [comment]
Let's see if I can come up with something. I'm thinking of a global state or something. Not the most clean code but it does the job well enough I think:


```javascript
data() {
    return {
        loading: false,
        needsExtraRender: false,
    };
},
watch: {
    async code() {
        await this.generateTokens();
    },
},
methods: {
    async generateTokens() {
        if (this.loading === true) {
            this.needsExtraRender = true;
            return;
        }

        this.$queue.push(async () => {
            this.loading = true;
            
            // Do the render ...

            this.loading = false;
            if (this.needsExtraRender) {
                this.needsExtraRender = false;
                this.generateTokens();
            }
        });
    },
},
```

Not sure about this, but I hope you get the general direction :)

Besides all this. Does the `generateTokens()` method need to be async? The `this.$queue.push()` should resolve immediately I think. (I do not know a lot about this stuff). That way you still would have an enormous queue, but it wouldn't be blocking the main thread.

**Comment by stevebauman** [comment]
I think your initial idea may work (although I'm unsure if it's just because I'm on a fast machine). I've pushed another update to the PR to remove the debounce and simply check if there is anything in the queue prior to pushing: 6d99210

> Besides all this. Does the generateTokens() method need to be async? The this.$queue.push() should resolve immediately I think.

Yes unfortunately, as `$shiki.loadLanguages()` and `$shiki.loadTheme()` will return promises if the languages or theme they are given have not yet been loaded:

https://github.com/stevebauman/showcode/blob/115a6d9ed7d1f8cc8789f998848a8e91564006a0/components/Preview.vue#L766-L768

**Comment by stevebauman** [comment]
Oh hang on sorry -- you're correct, the `generateTokens()` method does not need to be async, thanks!

**Comment by markwalet** [comment]
Making the `generateTokens()` not await anymore, the main-thread blocking issues should be resolved anyway, so that's good news!

I think you can throttle your performance in the chrome performance monitoring tab I think. Or you could go ~~my~~ the lazy route and just sleep for a few seconds in your queue job ;p

**Comment by stevebauman** [comment]
> I think you can throttle your performance in the chrome performance monitoring tab I think.

Thanks! I was able to test it out with performance throttling with your help.

 Debouncing along with making sure there was no more than one job in the queue seems to have reduced load quite a bit.

Closing this for now, as I've just merged the PR for these adjustments. If you have any further suggestions give me a shout! 😄
