### ISSUE TITLE
Bash language suppport

### ISSUE THREAD

**Issue by duboiss** [stevebauman/showcode#71]
It would be great to have bash support, what do you think?

**Comment by stevebauman** [comment]
Hi @duboiss, bash is already included under `shellscript`. It's a supported language provided out of the box with Shiki:

https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

Can you see if that supports the highlighting you're looking for?

**Comment by duboiss** [comment]
Looks good, thanks!
