### ISSUE TITLE
Copy to clipboard fails silently on Firefox

### ISSUE THREAD

**Issue by lupinitylabs** [stevebauman/showcode#73]
Firefox implemented support for ClipboardItem about a year ago (see https://bugzilla.mozilla.org/show_bug.cgi?id=1619947), but they still don't have it activated by default.

![grafik](https://user-images.githubusercontent.com/17774818/146068846-cc8144e8-b8c8-414f-a817-3cf5d8bd45e2.png)

Unless the user manually sets `dom.events.asyncClipboard.clipboardItem` in `about:config`, clicking the copy button in the app will throw a `ReferenceError: ClipboardItem is not defined` that is unhandled.

I would suggest adding a `.catch()` handler in the promise resolved at https://github.com/stevebauman/showcode/blob/32a4b902e27be472dd2e8337d470e77294a6092b/components/Preview.vue#L730, and/or to disable the copy button altogether (and probably showing a helpful message on how you can activate the feature) if `typeof ClipboardItem === 'undefined'`.

I would do a PR for it myself, but I don't want to mess around in your code without knowing how you would want that handled.

**Comment by stevebauman** [comment]
Thanks for letting me know @lupinitylabs. Do you know if `document.execCommand("copy")` would work in Firefox for images?

**Comment by lupinitylabs** [comment]
No, I'm afraid `document.execCommand("copy")` does not seem to do anything on images. It works for text, but that's about it.

**Comment by stevebauman** [comment]
Dang, so I guess our only solution is to disable the button or show a message upon clicking copy like you mentioned?

**Comment by lupinitylabs** [comment]
Yes, that's also how Carbon seems to do it. With the config key set to false, they don't show the copy image menu item, when it's true, it shows. 

It's a little frustrating that it takes Mozilla years to adopt web standards, and when they do, they don't activate them by default.

**Comment by lupinitylabs** [comment]
I would favor a solution where a message is shown that explains why copy isn't available over silently hiding or disabling the button, because it's not transparent for users why this feature would be missing or disabled.
