### ISSUE TITLE
Background Padding control conflicts with dragging

### ISSUE THREAD

**Issue by lupinitylabs** [stevebauman/showcode#79]
The background padding control is a little confusing, because it seems to compete with the drag resizing / is not properly synched with the image dimensions. I recorded a video to illustrate that.

Basically the background padding makes sure you cannot make the image smaller than the padding, which is good. 

However, the padding is not added to the dimensions shown beneath the drag handles. When resizing the image afterwards using the handles, there is a dead zone of `(backgroundPadding * 2) px` where the dimensions increase, but the image does not get bigger. That's easy to explain, since it does not get added to the actual dimensions as stated earlier, so the top and bottom padding needs to be caught up to first.

https://user-images.githubusercontent.com/17774818/146659733-0002a528-a39e-40ba-9b65-4447f3863207.mp4

**Comment by stevebauman** [comment]
This has been resolved -- I removed the background padding option completely to simply allow the width and height to be fully adjustable 👍
