### ISSUE TITLE
Feature request: Add emoticon menu?

### ISSUE THREAD

**Issue by lupinitylabs** [stevebauman/showcode#80]
👀 I guess it would be really 🔥 to add an emoticon menu somewhere on the code editor to easily add emoticons for illustration purposes. 🥰

**Comment by stevebauman** [comment]
Going to be implementing this!

Attaching this here for implementation:

https://github.com/CesiumLabs/emoji-api

Likely going to pull down all emojis during build process, plugging them into a `.json` file to be imported so users can search Emoji descriptions in UI.

**Comment by stevebauman** [comment]
How's something like this?

![Screenshot 2022-08-21 at 1 06 53 PM](https://user-images.githubusercontent.com/6421846/185802653-50dc76cf-5cca-4cc0-ace2-bef2fca5b15e.png)
