### ISSUE TITLE
Switching theme using arrow keys?

### ISSUE THREAD

**Issue by notDevagya** [stevebauman/showcode#90]
When you have selected a theme and press up/down key, it only switches the theme once and then the select becomes inactive. I think it would be better if you could just keep pressing up/down key to switch between themes. this might be a bug.

**Comment by stevebauman** [comment]
Hi @notDevagya!

This is actually intended, as the select is disabled while shiki regenerates the tokens for the new theme:

https://github.com/stevebauman/showcode/blob/b50d781d17f53eb3f6b7c693aa17a7c6241b585d/components/Preview.vue#L135-L141

But I think I can remove this now that I have a JS queue system implemented. I'll mark this as an enhancement for now 👍

**Comment by stevebauman** [comment]
Fixed in https://github.com/stevebauman/showcode/pull/91 👍
